version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
    groups:
      vite-plus:
        patterns:
          - "vite-plus"
          - "vite"
          - "@voidzero-dev/vite-plus-core"
          - "vitest"
      ajv:
        patterns:
          - "ajv"
          - "ajv-formats"
      typescript:
        patterns:
          - "typescript"
          - "@typescript/*"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
