packages:
  - packages/*
  - tools/*

allowBuilds:
  esbuild: true
  sharp: true

catalog:
  "@changesets/cli": 3.0.1
  "@drizzle-team/brocli": ^0.12.0
  "@markdoc/markdoc": ^0.5.9
  "@storybook/addon-a11y": 10.6.0
  "@storybook/addon-vitest": 10.6.0
  "@types/bun": ^1.4.0
  "@types/node": 22.20.1
  "@vitest/browser-playwright": 4.1.11
  entities: 8.0.0
  github-slugger: ^2.0.0
  json-schema-to-typescript: ^15.0.4
  playwright: ^1.63.0
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
  vitest: 4.1.11

catalogMode: prefer

minimumReleaseAgeExclude:
  - astro@6.4.4

overrides:
  jsdom: 28.1.0
  vite@*: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
    vite-plus: "*"
