/**
 * Generated from the adjacent JSON Schema by `vp run generate`.
 * Do not edit this file directly.
 */

/**
 * A course resource
 */
export interface Course {
  /**
   * API version
   */
  apiVersion: "v1";
  /**
   * Resource type
   */
  type: "Course";
  /**
   * Unique resource name (DNS-1123 subdomain)
   */
  name: string;
  labels?: {
    [k: string]: string;
  };
  spec: {
    /**
     * Title of the course
     */
    title: string;
    /**
     * URL-friendly slug
     */
    slug: string;
    /**
     * Description of the course
     */
    description?: string | null;
    /**
     * List of author references (Person names)
     */
    authors?: string[];
  };
}
