/**
 * Generated from the adjacent JSON Schema by `vp run generate`.
 * Do not edit this file directly.
 */

export interface Course {
  apiVersion: "v1";
  type: "Course";
  name: string;
  labels?: {
    [k: string]: string;
  };
  spec: {
    title: string;
    slug: string;
    description?: string | null;
    authors?: string[];
  };
}
