/**
 * Generated from the adjacent JSON Schema by `vp run generate`.
 * Do not edit this file directly.
 */

/**
 * An asset resource
 */
export interface Asset {
  apiVersion: "v1";
  type: "Asset";
  /**
   * Unique resource name (DNS-1123 subdomain)
   */
  name: string;
  labels?: {
    [k: string]: string;
  };
  spec: AssetSpec;
}
/**
 * This interface was referenced by `Asset`'s JSON-Schema
 * via the `definition` "AssetSpec".
 */
export interface AssetSpec {
  integrity?: string;
  mediaType?: string;
  size?: number;
  uri: string;
}
