/**
 * Generated from the adjacent JSON Schema by `vp run generate`.
 * Do not edit this file directly.
 */

export interface Asset {
  apiVersion: "v1";
  type: "Asset";
  name: string;
  labels?: {
    [k: string]: string;
  };
  spec: AssetSpec;
}
/**
 * This interface was referenced by `Asset`'s JSON-Schema
 * via the `definition` "AssetSpec".
 */
export interface AssetSpec {
  uri: string;
  integrity?: string;
  mediaType?: string;
  size?: number;
}
