/**
 * Generated from the adjacent JSON Schema by `vp run generate`.
 * Do not edit this file directly.
 */

/**
 * A content page within a course module
 */
export interface CoursePage {
  /**
   * API version
   */
  apiVersion: "v1";
  /**
   * Resource type
   */
  type: "CoursePage";
  /**
   * Unique resource name (DNS-1123 subdomain)
   */
  name: string;
  /**
   * Key-value labels for organization
   */
  labels?: {
    [k: string]: string;
  };
  spec: {
    /**
     * Reference to a CourseModule by name
     */
    module: string;
    /**
     * Page title
     */
    title: string;
    /**
     * URL-friendly slug
     */
    slug: string;
    /**
     * Order of the page within the module
     */
    order: number;
    /**
     * List of author references (Person names)
     */
    authors?: string[];
    content: {
      /**
       * Format of the content value
       */
      format: "topik" | "other";
      /**
       * Page content in the specified format
       */
      value: string;
    };
  };
}
