/**
 * Generated from the adjacent JSON Schema by `vp run generate`.
 * Do not edit this file directly.
 */

export interface CoursePage {
  apiVersion: "v1";
  type: "CoursePage";
  name: string;
  labels?: {
    [k: string]: string;
  };
  spec: {
    module: string;
    title: string;
    slug: string;
    order: number;
    authors?: string[];
    content: {
      format: "topik" | "other";
      value: string;
    };
  };
}
