/**
 * Generated from the adjacent JSON Schema by `vp run generate`.
 * Do not edit this file directly.
 */

export interface CourseModule {
  apiVersion: "v1";
  type: "CourseModule";
  name: string;
  labels?: {
    [k: string]: string;
  };
  spec: {
    course: string;
    title: string;
    slug: string;
    order: number;
    description?: string | null;
  };
}
