/**
 * Generated from the adjacent JSON Schema by `vp run generate`.
 * Do not edit this file directly.
 */

/**
 * A module within a course
 */
export interface CourseModule {
  /**
   * API version
   */
  apiVersion: "v1";
  /**
   * Resource type
   */
  type: "CourseModule";
  /**
   * Unique resource name (DNS-1123 subdomain)
   */
  name: string;
  /**
   * Key-value labels for organization
   */
  labels?: {
    [k: string]: string;
  };
  spec: {
    /**
     * Reference to a Course by name
     */
    course: string;
    /**
     * Module title
     */
    title: string;
    /**
     * URL-friendly slug
     */
    slug: string;
    /**
     * Order of the module within the course
     */
    order: number;
    /**
     * Description of the module
     */
    description?: string | null;
  };
}
