/**
 * Generated from the adjacent JSON Schema by `vp run generate`.
 * Do not edit this file directly.
 */

export interface Person {
  apiVersion: "v1";
  type: "Person";
  /**
   * Unique resource name (DNS-1123 subdomain)
   */
  name: string;
  labels?: {
    [k: string]: string;
  };
  spec: {
    /**
     * Display name of the person
     */
    name: string;
    /**
     * Email address
     */
    email?: string | null;
    /**
     * Biography or description
     */
    bio?: string | null;
  };
}
