/**
 * Generated from the adjacent JSON Schema by `vp run generate`.
 * Do not edit this file directly.
 */

export interface Person {
  apiVersion: "v1";
  type: "Person";
  name: string;
  labels?: {
    [k: string]: string;
  };
  spec: {
    name: string;
    email?: string | null;
    bio?: string | null;
  };
}
