/**
 * Generated from the adjacent JSON Schema by `vp run generate`.
 * Do not edit this file directly.
 */

/**
 * A homogeneous root of tabs, dropdowns, or sidebar nodes
 *
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "navigation".
 */
export type WikiNavigation = WikiTabNavNode[] | WikiDropdownNavNode[] | WikiSidebarNavNode[];
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "tabNode".
 */
export type WikiTabNavNode = WikiInternalTabNavNode | WikiExternalTabNavNode;
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "dropdownNode".
 */
export type WikiDropdownNavNode = WikiInternalDropdownNavNode | WikiExternalDropdownNavNode;
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "sidebarNode".
 */
export type WikiSidebarNavNode = WikiGroupNavNode | WikiPageNavNode | WikiLinkNavNode;
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "navContainerNode".
 */
export type WikiNavContainerNode =
  | WikiGroupNavNode
  | WikiInternalDropdownNavNode
  | WikiInternalTabNavNode;
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "navNode".
 */
export type WikiNavNode = WikiTabNavNode | WikiDropdownNavNode | WikiSidebarNavNode;

export interface Wiki {
  apiVersion: "v1";
  type: "Wiki";
  /**
   * Unique resource name (DNS-1123 subdomain)
   */
  name: string;
  labels?: {
    [k: string]: string;
  };
  spec: {
    /**
     * Title of the wiki
     */
    title: string;
    /**
     * Description of the wiki
     */
    description?: string | null;
    navigation?: WikiNavigation;
    theme?: WikiTheme;
  };
}
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "internalTabNode".
 */
export interface WikiInternalTabNavNode {
  type: "tab";
  title: string;
  slug?: string;
  icon?: string;
  hidden?: boolean;
  children: WikiDropdownNavNode[] | WikiSidebarNavNode[];
}
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "internalDropdownNode".
 */
export interface WikiInternalDropdownNavNode {
  type: "dropdown";
  title: string;
  slug?: string;
  icon?: string;
  hidden?: boolean;
  children: WikiSidebarNavNode[];
}
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "groupNode".
 */
export interface WikiGroupNavNode {
  type: "group";
  title: string;
  slug?: string;
  icon?: string;
  expanded?: boolean;
  hidden?: boolean;
  children: WikiSidebarNavNode[];
}
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "pageNode".
 */
export interface WikiPageNavNode {
  type: "page";
  /**
   * Reference to a WikiPage by name
   */
  page: string;
  /**
   * URL path relative to the containing navigation node
   */
  slug: string;
  /**
   * Full extensionless Markdown source path
   */
  sourcePath?: string;
  icon?: string;
  hidden?: boolean;
}
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "linkNode".
 */
export interface WikiLinkNavNode {
  type: "link";
  title: string;
  icon?: string;
  hidden?: boolean;
  href: string;
}
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "externalDropdownNode".
 */
export interface WikiExternalDropdownNavNode {
  type: "dropdown";
  title: string;
  icon?: string;
  hidden?: boolean;
  href: string;
}
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "externalTabNode".
 */
export interface WikiExternalTabNavNode {
  type: "tab";
  title: string;
  icon?: string;
  hidden?: boolean;
  href: string;
}
/**
 * Theme configuration
 *
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface WikiTheme {
  colors?: {
    /**
     * Primary theme color
     */
    primary: string;
    /**
     * Light mode color override
     */
    light?: string;
    /**
     * Dark mode color override
     */
    dark?: string;
  };
  appearance?: {
    /**
     * Default color scheme
     */
    default?: "light" | "dark" | "system";
  };
}
