/**
 * Generated from the adjacent JSON Schema by `vp run generate`.
 * Do not edit this file directly.
 */

/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "navigation".
 */
export type WikiNavigation = WikiTabNavNode[] | WikiDropdownNavNode[] | WikiSidebarNavNode[];
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "tabNode".
 */
export type WikiTabNavNode = WikiInternalTabNavNode | WikiExternalTabNavNode;
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "dropdownNode".
 */
export type WikiDropdownNavNode = WikiInternalDropdownNavNode | WikiExternalDropdownNavNode;
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "sidebarNode".
 */
export type WikiSidebarNavNode = WikiGroupNavNode | WikiPageNavNode | WikiLinkNavNode;
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "navContainerNode".
 */
export type WikiNavContainerNode =
  | WikiGroupNavNode
  | WikiInternalDropdownNavNode
  | WikiInternalTabNavNode;
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "navNode".
 */
export type WikiNavNode = WikiTabNavNode | WikiDropdownNavNode | WikiSidebarNavNode;

export interface Wiki {
  apiVersion: "v1";
  type: "Wiki";
  name: string;
  labels?: {
    [k: string]: string;
  };
  spec: {
    title: string;
    description?: string | null;
    navigation?: WikiNavigation;
    theme?: WikiTheme;
  };
}
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "internalTabNode".
 */
export interface WikiInternalTabNavNode {
  type: "tab";
  title: string;
  slug?: string;
  icon?: string;
  hidden?: boolean;
  children: WikiDropdownNavNode[] | WikiSidebarNavNode[];
}
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "internalDropdownNode".
 */
export interface WikiInternalDropdownNavNode {
  type: "dropdown";
  title: string;
  slug?: string;
  icon?: string;
  hidden?: boolean;
  children: WikiSidebarNavNode[];
}
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "groupNode".
 */
export interface WikiGroupNavNode {
  type: "group";
  title: string;
  slug?: string;
  icon?: string;
  expanded?: boolean;
  hidden?: boolean;
  children: WikiSidebarNavNode[];
}
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "pageNode".
 */
export interface WikiPageNavNode {
  type: "page";
  page: string;
  slug: string;
  sourcePath?: string;
  icon?: string;
  hidden?: boolean;
}
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "linkNode".
 */
export interface WikiLinkNavNode {
  type: "link";
  title: string;
  icon?: string;
  hidden?: boolean;
  href: string;
}
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "externalDropdownNode".
 */
export interface WikiExternalDropdownNavNode {
  type: "dropdown";
  title: string;
  icon?: string;
  hidden?: boolean;
  href: string;
}
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "externalTabNode".
 */
export interface WikiExternalTabNavNode {
  type: "tab";
  title: string;
  icon?: string;
  hidden?: boolean;
  href: string;
}
/**
 * This interface was referenced by `Wiki`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface WikiTheme {
  colors?: {
    primary: string;
    light?: string;
    dark?: string;
  };
  appearance?: {
    default?: "light" | "dark" | "system";
  };
}
