/**
 * Generated from the adjacent JSON Schema by `vp run generate`.
 * Do not edit this file directly.
 */

export interface Guide {
  apiVersion: "v1";
  type: "Guide";
  name: string;
  labels?: {
    [k: string]: string;
  };
  spec: {
    title: string;
    slug: string;
    description?: string | null;
    authors?: string[];
    tags?: string[];
    content: {
      format: "topik" | "other";
      value: string;
    };
  };
}
