/**
 * Generated from the adjacent JSON Schema by `vp run generate`.
 * Do not edit this file directly.
 */

export interface WikiPage {
  apiVersion: "v1";
  type: "WikiPage";
  name: string;
  labels?: {
    [k: string]: string;
  };
  spec: {
    wiki: string;
    title: string;
    description?: string | null;
    content: {
      format: "topik" | "other";
      value: string;
    };
  };
}
