/**
 * Generated from the adjacent JSON Schema by `vp run generate`.
 * Do not edit this file directly.
 */

/**
 * A content page within a wiki
 */
export interface WikiPage {
  /**
   * API version
   */
  apiVersion: "v1";
  /**
   * Resource type
   */
  type: "WikiPage";
  /**
   * Unique resource name (DNS-1123 subdomain)
   */
  name: string;
  /**
   * Key-value labels for organization
   */
  labels?: {
    [k: string]: string;
  };
  spec: {
    /**
     * Reference to a Wiki by name
     */
    wiki: string;
    /**
     * Page title
     */
    title: string;
    /**
     * Description of the wiki page
     */
    description?: string | null;
    content: {
      /**
       * Format of the content value
       */
      format: "topik" | "other";
      /**
       * Page content in the specified format
       */
      value: string;
    };
  };
}
