import { execFile } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { compileFromFile } from "json-schema-to-typescript";
import { discoverSchemaTargets } from "./schema-targets.mjs";

const packageUrl = new URL("../", import.meta.url);
const packageDirectory = fileURLToPath(packageUrl);
const check = process.argv.includes("--check");

const targets = await discoverSchemaTargets(packageDirectory);

const bannerComment = `/**
 * Generated from the adjacent JSON Schema by \`vp run generate\`.
 * Do not edit this file directly.
 */`;

const run = promisify(execFile);

let stale = false;
const temporaryDirectory = await mkdtemp(join(tmpdir(), "topik-schema-types-"));

try {
  const generatedTargets = await Promise.all(
    targets.map(async (target, index) => {
      const schemaPath = fileURLToPath(new URL(target.schema, packageUrl));
      const temporaryPath = join(temporaryDirectory, `${index}.ts`);
      const generated = await compileFromFile(schemaPath, {
        bannerComment,
        cwd: packageDirectory,
        format: false,
        unreachableDefinitions: true,
      });
      await writeFile(temporaryPath, generated);
      return { ...target, temporaryPath };
    }),
  );

  await run("vp", ["fmt", temporaryDirectory, "--write"], { cwd: packageDirectory });

  for (const target of generatedTargets) {
    const typesPath = fileURLToPath(new URL(target.types, packageUrl));
    const generated = await readFile(target.temporaryPath, "utf8");

    if (check) {
      const current = await readFile(typesPath, "utf8").catch(() => "");
      if (current !== generated) {
        console.error(`${target.types} is stale; run \`vp run generate\` in packages/schema`);
        stale = true;
      }
      continue;
    }

    await writeFile(typesPath, generated);
  }
} finally {
  await rm(temporaryDirectory, { recursive: true, force: true });
}

if (stale) process.exitCode = 1;
